<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <ProjectReference Include="..\Nexus.Sync\Nexus.Sync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\nexus.ico</ApplicationIcon>
    <Version>1.0.10</Version>
    <StartupObject>Nexus.App.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\nexus.ico" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

</Project>
